<a href="https://colab.research.google.com/github/AlyssonBatista/Codigos-python/blob/main/Biblioteca_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Biblioteca numpy

##### Exemplo de criação de um array numpy

In [5]:
import numpy as np

a = np.array([1,2,3,4,5,6,6])

print(a)
print(type(a))

[1 2 3 4 5 6 6]
<class 'numpy.ndarray'>


##### Array bidimensional

In [9]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##### Principais métodos 

In [12]:
print(b.ndim) # Nos informa a dimensão do array

print(a.ndim)

2
1


In [13]:
print(b.shape) # numero de linhas e colunas

(3, 3)


In [14]:
print(len(b)) # OBS: len só retornar o numero de linhas

3


In [16]:
c=np.arange(0,151,3) # Cria um array com inicio(0) fim(151) e passo(3)
print(c)

[  0   3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51
  54  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105
 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150]


In [18]:
d = np.arange(10) #  Com um paramnetro ele retorna um array de 0 até 9 com passo 1
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
e=np.arange(2,10) # Com dois parametros retorna um array com inicio(2) e fim(10) não inclui o último número
print(e)

[2 3 4 5 6 7 8 9]


In [32]:
f = np.linspace(1,15,10) # retorna um array com inicio(1) fim(15) e quantidade de elemnentos(10)
print(f)

[ 1.          2.55555556  4.11111111  5.66666667  7.22222222  8.77777778
 10.33333333 11.88888889 13.44444444 15.        ]


In [35]:
g = np.linspace(1,10,10, endpoint=False) # não inclui o último número(10)
print(g)

[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]


In [37]:
h = np.ones(4) # cria um array de 1's de uma dimensão 
print(h)

[1. 1. 1. 1.]


In [42]:
i = np.ones((4,5)) # cria um array de duas dimensões 4(número de linhas) 5(número de colunas)
print(i)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [44]:
j= np.zeros((4,5))
print(j)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [48]:
h= np.random.rand(10,5) # Cria um array bidimensional de número aleatórios com número de linhas(10) e colunas(5)
print(h)

[[0.56076756 0.40480686 0.34587579 0.42695114 0.38478524]
 [0.75975105 0.46896373 0.86092971 0.34869653 0.73036404]
 [0.88912696 0.03274634 0.26503058 0.2579538  0.87592625]
 [0.4066879  0.51586278 0.72866638 0.73457359 0.3033133 ]
 [0.90694687 0.82799164 0.03952139 0.77682607 0.93923391]
 [0.21609217 0.60272703 0.9299377  0.10429728 0.64709678]
 [0.52898809 0.99579222 0.56923823 0.75244361 0.32985186]
 [0.93107746 0.70915145 0.43137689 0.19837682 0.81931523]
 [0.46546615 0.17878537 0.052589   0.31883899 0.04574612]
 [0.54945346 0.71406131 0.43874339 0.58545182 0.69064244]]


In [50]:
i=np.random.rand(10) # cria um array de némeros aleatórios com 10 elementos
print(i)

[0.75154744 0.034729   0.02284107 0.39604345 0.75811025 0.44684064
 0.23027664 0.58236287 0.31260446 0.62064021]


In [51]:
k = np.eye(4) # cria uma matriz diagonal 
print(k)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [53]:
l= np.diag(np.array([1,2,3,4])) #insere os números na diagonal
print(l)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
