<a href="https://colab.research.google.com/github/AlyssonBatista/Codigos-python/blob/main/Codigo_de_hamming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np
import random
import itertools

def espaco_vetorial(n): # Função que retorna um espaço vetorial 2^n composto pelo maior número possível de vetores com n elementos de {0,1}
    alista = []
    vetor = []
    for numbers in itertools.product([0, 1], repeat=n):
        alista = list(numbers)
        vetor.append(alista)
    espaco_vetor = np.asarray(vetor)
 
    return espaco_vetor


def subespaco_vetorial(n,k): # Função que retorna um subespaço vetorial 2^k a partir do espaço vetorial 2^n
    subespaco_vetores = []
    indicie = []
    indicie = random.sample(range(1,2**n), 2**k-1) # indicie dos vetores do espaço vetorial de 1 a 2^n com 2^k-1 elementos NÃO REPETIDOS
    for i in range(2**k-1):
        copia_espaco = np.array(espaco_vetorial(n)) # copia do espaço vetoria
        subespaco_vetores.append(copia_espaco[indicie[i]]) # adiciona ao vetor um vetor do espaço vetorial por um indicie aleatório
    subespaco_vetores.insert(0,copia_espaco[0]) # adiciona o vetor nulo no indicie 0 do subespaço
    return subespaco_vetores


def base_subespaco_vetorial(lista,k): # Função que retorna a base do subespaço vetorial k a partir do subespaço vetorial 2^k
    base = []
    indicie = random.sample(range(0,2**k), k) # indicie dos vetores do espaço vetorial de 1 a 2^k com k elementos NÃO REPETIDOS
    for i in range(k):
        copia_subespaco = np.array(lista) # copia do subespaço vetorial
        base.append(copia_subespaco[indicie[i]]) # adiciona ao vetor base k vetores do subespaço vetorial por um indicie aleatório
    return base


def imprime_matriz(lista):
    linhas = len(lista)
    colunas = len(lista[0])

    for i in range(linhas):
        for j in range(colunas):
            if(j == colunas - 1):
                print("%s" %lista[i][j] )
            else:
                print("%s" %lista[i][j] , end = " ")
    print('\n')


n=int(input("O digite o tamanho do espaço vetorial n: \n"))
k=int(input("O digite o valor de k do subespaço vetorial: \n"))


espaco = np.array(espaco_vetorial(n))
subespaco = np.array(subespaco_vetorial(n,k))
base = np.array(base_subespaco_vetorial(subespaco,k))
print('\n')
print(f'Espaço vetorial = 2^{n}')
imprime_matriz(espaco)
print(f'Subespaço vetorial = 2^{k}')
imprime_matriz(subespaco)
print(f'Base do subespaço vetorial k = {k}')
imprime_matriz(base)

O digite o tamanho do espaço vetorial n: 
4
O digite o valor de k do subespaço vetorial: 
2


Espaço vetorial = 2^4
0 0 0 0
0 0 0 1
0 0 1 0
0 0 1 1
0 1 0 0
0 1 0 1
0 1 1 0
0 1 1 1
1 0 0 0
1 0 0 1
1 0 1 0
1 0 1 1
1 1 0 0
1 1 0 1
1 1 1 0
1 1 1 1


Subespaço vetorial = 2^2
0 0 0 0
1 0 0 0
1 0 0 1
1 0 1 0


Base do subespaço vetorial k = 2
1 0 1 0
0 0 0 0




[0 0 0 0] [0 1 0 0]
[0 0 0 1] [0 1 0 1]
[0 0 1 0] [0 1 1 0]
[0 0 1 1] [0 1 1 1]
[0 0 1 1]
[0 1 0 1]


In [ ]:
def subespaco_vetorial(n,k): # Função que retorna um subespaço vetorial 2^k a partir do espaço vetorial 2^n
    subespaco_vetores = []
    indicie = []
    indicie = random.sample(range(1,2**n), 2**k-1) # indicie dos vetores do espaço vetorial de 1 a 2^n com 2^k-1 elementos NÃO REPETIDOS
    for i in range(2**k-1):
        copia_espaco = np.array(espaco_vetorial(n)) # copia do espaço vetoria
        subespaco_vetores.append(copia_espaco[indicie[i]]) # adiciona ao vetor um vetor do espaço vetorial por um indicie aleatório
        
    subespaco_vetores.insert(0,copia_espaco[0]) # adiciona o vetor nulo no indicie 0 do subespaço
    return subespaco_vetores

In [165]:
indicie = random.sample(range(1,2**n), 2**k-1)
arra = espaco_vetorial(n)
lis = []
zeros = espaco_vetorial(n)
sub = np.random.randint(2, size=n) 
for i in range((2**k)-1):
    soma = sub + arra[i]
    vetor = soma%2
    lis.append(vetor)
lis.insert(0,zeros[0]) # adiciona o vetor nulo no indicie 0 do subespaço
lis


[array([0, 0, 0, 0]),
 array([1, 0, 0, 0]),
 array([1, 0, 0, 1]),
 array([1, 0, 1, 0])]

In [157]:
sub

array([0, 1, 0, 1])