<a href="https://colab.research.google.com/github/AlyssonBatista/Codigos-python/blob/main/c%C3%B3digo_de_bloco_linear_(7%2C4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import math
import numpy as np

# Matriz geradora
G = np.array([[1,0,0,0,1,0,1],[0,1,0,0,1,1,1],[0,0,1,0,1,1,0],[0,0,0,1,0,1,1]])
print('Matriz G geradora')                                                                               
print('',G[0] ,' \n',G[1],' \n',G[2])

# matriz verificadora de paridade transposta H^T
print('\n')
print('Matriz verificadora de paridade transposta H^T')
H = np.array([[1, 0, 1],[1, 1, 1],[1, 1, 0],[0, 1, 1],[1, 0, 0],[0, 1, 0],[0, 0, 1]])                                        
print('',H[0] ,' \n',H[1],' \n',H[2],' \n',H[3],' \n',H[4],' \n',H[5])

# Lista de erros corrigíveis
print('\n')
print('Lista E de erros corrigíveis')
E = np.array([[1,0,0,0,0,0,0],[0,1,0,0,0,0,0],[0,0,1,0,0,0,0],[0,0,0,1,0,0,0],[0,0,0,0,1,0,0],[0,0,0,0,0,1,0],[0,0,0,0,0,0,1]]);     
print('',E[0] ,' \n',E[1],' \n',E[2],' \n',E[3],' \n',E[4],' \n',E[5],' \n',E[6])

K = np.size(E)/np.size(E, axis=1) 

# Localiza Lista de Síndromes
sindrome = (E.dot(H)) % 2                                                                                
r = np.array([1,0,1,0,1,1,1]);
print('\n')
print(f'Sindrome','Padrão de erro')

for i in range(7):
    print(sindrome[i],'',E[i])
 

x_aux = []
for i in range(len(H)):
    xmult =  r[i] * H[i]
    x_aux.append(xmult)
x_array = np.asarray(x_aux)
soma = x_array.cumsum(axis=0)	
x = soma[6]% 2

for i in range(7):
    idxe = all(sindrome[i] == x)
    if idxe==True:
        idxe = i
        break;

sindrome = sindrome[idxe,:]
erro = E[idxe,:]
palavra_corrigida = np.logical_xor(r,erro); 
palavra_corrigida = palavra_corrigida*1


print('\n')
print(f'Palavra código recebida',r)
print(f'Sindrome',sindrome )
print(f'Padrão de erro',erro)
print(f'Palavra corrigida',palavra_corrigida)

Matriz G geradora
 [1 0 0 0 1 0 1]  
 [0 1 0 0 1 1 1]  
 [0 0 1 0 1 1 0]


Matriz verificadora de paridade transposta H^T
 [1 0 1]  
 [1 1 1]  
 [1 1 0]  
 [0 1 1]  
 [1 0 0]  
 [0 1 0]


Lista E de erros corrigíveis
 [1 0 0 0 0 0 0]  
 [0 1 0 0 0 0 0]  
 [0 0 1 0 0 0 0]  
 [0 0 0 1 0 0 0]  
 [0 0 0 0 1 0 0]  
 [0 0 0 0 0 1 0]  
 [0 0 0 0 0 0 1]


Sindrome Padrão de erro
[1 0 1]  [1 0 0 0 0 0 0]
[1 1 1]  [0 1 0 0 0 0 0]
[1 1 0]  [0 0 1 0 0 0 0]
[0 1 1]  [0 0 0 1 0 0 0]
[1 0 0]  [0 0 0 0 1 0 0]
[0 1 0]  [0 0 0 0 0 1 0]
[0 0 1]  [0 0 0 0 0 0 1]


Palavra código recebida [1 0 1 0 1 1 1]
Sindrome [1 0 0]
Padrão de erro [0 0 0 0 1 0 0]
Palavra corrigida [1 0 1 0 0 1 1]
