<a href="https://colab.research.google.com/github/AlyssonBatista/Codigos-python/blob/main/M%C3%A9todos_do_objeto_array_e_m%C3%A1scaras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Métodos importantes array

In [21]:
import numpy as np

ar = np.random.randn(10)
ar

array([-0.4267449 , -0.46823059,  0.20349333, -0.4452106 , -0.52971032,
       -0.17675522, -1.44062069, -0.24910702, -0.07999033, -0.56560866])

In [22]:
ma = np.random.randn(3,3)
ma

array([[-0.11348013,  1.04983129,  1.43651944],
       [-0.79732884,  0.28544047,  0.21194447],
       [ 1.04578619,  0.77274401,  1.98900887]])

In [25]:
print(ar.ndim) # Diz a dimensão do array ou matriz
print(ma.ndim)

1
2


In [27]:
print(ar.shape) # Retorna o formato do array 
print(ma.shape)

(10,)
(3, 3)


In [29]:
print(ar.dtype) # Retorna o tipo de array 
print(ma.dtype)

float64
float64


In [31]:
print(ar.astype('int')) # asstype ignora os valores depois da virgula retornando apena o inteiro
print(ma.astype('int'))

[ 0  0  0  0  0  0 -1  0  0  0]
[[0 1 1]
 [0 0 0]
 [1 0 1]]


In [32]:
print(ar.astype('bool')) # asstype retorna True se o número != 0 e False se número == 0
print(ma.astype('bool'))

[ True  True  True  True  True  True  True  True  True  True]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [37]:
print(ar.min()) # retorna o menor número do array ou matriz
print(ma.min())

-1.4406206937020163
-0.7973288408915362


In [38]:
print(ar.max()) # retorna o maior número do array ou matriz
print(ma.max())

0.20349332808408663
1.9890088744113323


In [42]:
print(ar.argmin()) # retorna a posição que está o menor elemento do array ou matriz
print(ma.argmin())

6
3


In [43]:
print(ar.argmax()) # retorna a posição que está o maior elemento do array ou matriz
print(ma.argmax())

2
8


In [47]:
print(ar.mean()) # retorna a média dos elementos do array ou matriz
print(ma.mean())

-0.41784850031050225
0.6533850861997357


In [48]:
print(ar.sum()) # retorna a soma dos elementos do array ou matriz
print(ma.sum())

-4.178485003105022
5.880465775797621


In [49]:
print(ar.var()) # retorna a variância dos elementos do array ou matriz
print(ma.var())

0.16705887405345096
0.6383879214436418


In [50]:
print(ar.std()) # retorna a desvio padrão dos elementos do array ou matriz
print(ma.std())

0.4087283621837992
0.7989918156299486


In [54]:
print(np.sort(ar)) # sort ordena do menor para o maior
print(np.sort(ma))

[-1.44062069 -0.56560866 -0.52971032 -0.46823059 -0.4452106  -0.4267449
 -0.24910702 -0.17675522 -0.07999033  0.20349333]
[[-0.11348013  1.04983129  1.43651944]
 [-0.79732884  0.21194447  0.28544047]
 [ 0.77274401  1.04578619  1.98900887]]


In [57]:
print(ma.T) # Retorna a transposta da matriz 

[[-0.11348013 -0.79732884  1.04578619]
 [ 1.04983129  0.28544047  0.77274401]
 [ 1.43651944  0.21194447  1.98900887]]
[-0.4267449  -0.46823059  0.20349333 -0.4452106  -0.52971032 -0.17675522
 -1.44062069 -0.24910702 -0.07999033 -0.56560866]


# Máscaras 

In [66]:
a = np.array([1,2,3,4,5,6]) 
a
a[[False,False,False,True,True,True]] # A máscara retorna os elementos verdadeiros 

array([4, 5, 6])

In [68]:
a <= 3 # Os elementos menores ou iguais a 3 ficam verdadeiros 

array([ True,  True,  True, False, False, False])

In [67]:
a[a<=3] # A máscara retorna os elementos do array que são menores ou iguais a 3

array([1, 2, 3])

In [69]:
a % 2 == 0 #  A máscara retorna verdadeiro para os elementos onde a condição é satisfeita

array([False,  True, False,  True, False,  True])

In [70]:
a[a % 2 == 0] 

array([2, 4, 6])