<a href="https://colab.research.google.com/github/AlyssonBatista/Codigos-python/blob/main/Opera%C3%A7%C3%B5es_com_arrays_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

np.random.seed(32)
a1 = np.random.randint(1,40,10) # gera 30 números aleatórios inteiros entre 1 e 40 
print(a1)
print(a1 - 2) 
print(a1 * 3)
print(a1 / 2)
print(a1 + 4)

[24  6 25 20  8 26  4 38 10  5]
[22  4 23 18  6 24  2 36  8  3]
[ 72  18  75  60  24  78  12 114  30  15]
[12.   3.  12.5 10.   4.  13.   2.  19.   5.   2.5]
[28 10 29 24 12 30  8 42 14  9]


#### Operações entre arrays 

In [24]:
a2 = np.random.randint(1,100,10)
a1 = np.random.randint(1,40,10)
print(a1)
print(a2)
print('\n')
soma_array = a1 + a2
print(soma_array)

#OBS: OS ARRAYS PRECISAM TER MESMO TAMANHO!
# EXCETO PARA MULTIPLICAÇÃO DE MATRIZES 

[ 1 31 37 23 16 15 36 11 34 10]
[78 38 75 48 69  6 10 11 85 32]


[ 79  69 112  71  85  21  46  22 119  42]


In [26]:
multiplica = a1*a2
print(multiplica)

[  78 1178 2775 1104 1104   90  360  121 2890  320]


In [27]:
subtra = a1-a2
print(subtra)

[-77  -7 -38 -25 -53   9  26   0 -51 -22]


In [29]:
divide =a1 / a2
print(divide)

[0.01282051 0.81578947 0.49333333 0.47916667 0.23188406 2.5
 3.6        1.         0.4        0.3125    ]


#### Multiplicação entre matrizes 

In [35]:
# (3x2)*(2,3)=(3,3) 
# Na multiplicação de matrizes o numero de linhas da primeira matriz tem que ser igual ao número de colunas da segunda matriz

m1 = np.random.randint(1,50,(3,2))
print(m1)

print('\n')

m2 = np.random.randint(1,50,(2,3))
print(m2)

m1.dot(m2) # método que calcula matriz


[[25  1]
 [41 28]
 [ 6 48]]


[[31 33 47]
 [23 34 35]]


array([[ 798,  859, 1210],
       [1915, 2305, 2907],
       [1290, 1830, 1962]])

#### Comparações 

In [40]:
mc = np.array([1,2,3,4])
md = np.array([4,2,3,4])

mc == md


array([False,  True,  True,  True])

In [42]:
# ou:

np.array_equal(mc,md)

False

In [46]:
np.sin(md)

array([-0.7568025 ,  0.90929743,  0.14112001, -0.7568025 ])

[Mathematical functions](https://numpy.org/doc/1.18/reference/routines.math.html)